[tool.pyright]
pythonVersion = "3.13"
include = ["auth_server"]
exclude = ["**/node_modules", "**/__pycache__", "**/migrations"]

[tool.mypy]
python_version = "3.13"
warn_return_any = false
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = false
warn_no_return = true
warn_unreachable = true
strict_equality = true

# Django specific settings
plugins = ["django_stubs_ext.django_stubs_config"]

[tool.django-stubs]
django_settings_module = "auth_server.config.settings"

[[tool.mypy.overrides]]
module = ["rest_framework.*", "rest_framework_simplejwt.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "django.*"
ignore_missing_imports = false
