# Generated by Django 5.2.5 on 2025-09-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
