# Generated by Django 5.2.5 on 2025-09-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='uploaded/'),
        ),
    ]
